@startuml
set namespaceSeparator ::

class "redflag::pin::pinVerficationPage.dart::Verificatoin" {
  +String status
  +_VerificatoinState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "redflag::pin::pinVerficationPage.dart::Verificatoin"

class "redflag::pin::pinVerficationPage.dart::_VerificatoinState" {
  +TextEditingController confirmPinEditingController
  -bool _pinLength
  -Timer? _timer
  -FlutterSoundRecorder _myRecorder
  +AssetsAudioPlayer audioPlayer
  +String filePath
  +dynamic emergencyId
  +dynamic endDate
  +User? user
  +Users loggedInUser
  +EmergencyContacts emergencyContactModel
  +List<dynamic> recipients
  +String? userFirstName
  +String? userLastName
  +Emergency emergencyCase
  +String subject
  +String? downloadUrl
  +void initState()
  +dynamic verify()
  +void startIt()
  +Future<void> record()
  +Future<String?> stopRecord()
  +Timer scheduleTimeout()
  +Future<dynamic> uploadRecording()
  +void startTimer()
  +Widget build()
}

"redflag::pin::pinVerficationPage.dart::_VerificatoinState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"redflag::pin::pinVerficationPage.dart::_VerificatoinState" o-- "dart::async::Timer"
"redflag::pin::pinVerficationPage.dart::_VerificatoinState" o-- "flutter_sound::public::flutter_sound_recorder.dart::FlutterSoundRecorder"
"redflag::pin::pinVerficationPage.dart::_VerificatoinState" o-- "assets_audio_player::src::assets_audio_player.dart::AssetsAudioPlayer"
"redflag::pin::pinVerficationPage.dart::_VerificatoinState" o-- "firebase_auth::firebase_auth.dart::User"
"redflag::pin::pinVerficationPage.dart::_VerificatoinState" o-- "redflag::Users.dart::Users"
"redflag::pin::pinVerficationPage.dart::_VerificatoinState" o-- "redflag::EmergencyContacts.dart::EmergencyContacts"
"redflag::pin::pinVerficationPage.dart::_VerificatoinState" o-- "redflag::Emergency.dart::Emergency"
"flutter::src::widgets::framework.dart::State" <|-- "redflag::pin::pinVerficationPage.dart::_VerificatoinState"

class "redflag::registration_pages::registration_screen.dart::RegistrationScreen" {
  +_RegistrationScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "redflag::registration_pages::registration_screen.dart::RegistrationScreen"

class "redflag::registration_pages::registration_screen.dart::_RegistrationScreenState" {
  -FirebaseAuth _auth
  +String? errorMessage
  +int currentStep
  +TextEditingController firstNameEditingController
  +TextEditingController secondNameEditingController
  +TextEditingController emailEditingController
  +TextEditingController passwordEditingController
  +TextEditingController confirmPasswordEditingController
  +TextEditingController confirmPinEditingController
  +TextEditingController keywordEditingController
  +TextEditingController confirmKeywordEditingController
  +TextEditingController emergencyContactNameEditingController
  +TextEditingController emergencyContactEmailEditingController
  +Widget build()
  +void signUp()
  +dynamic postDetailsToFirestore()
}

"redflag::registration_pages::registration_screen.dart::_RegistrationScreenState" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"redflag::registration_pages::registration_screen.dart::_RegistrationScreenState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "redflag::registration_pages::registration_screen.dart::_RegistrationScreenState"

class "redflag::registration_pages::login_screen.dart::LoginScreen" {
  +_LoginScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "redflag::registration_pages::login_screen.dart::LoginScreen"

class "redflag::registration_pages::login_screen.dart::_LoginScreenState" {
  -GlobalKey<FormState> _formKey
  +TextEditingController emailController
  +TextEditingController passwordController
  -FirebaseAuth _auth
  +String? errorMessage
  +Widget build()
  +void signIn()
}

"redflag::registration_pages::login_screen.dart::_LoginScreenState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"redflag::registration_pages::login_screen.dart::_LoginScreenState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"redflag::registration_pages::login_screen.dart::_LoginScreenState" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"flutter::src::widgets::framework.dart::State" <|-- "redflag::registration_pages::login_screen.dart::_LoginScreenState"

class "redflag::registration_pages::landing_screen.dart::LandingScreen" {
  +_LandingScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "redflag::registration_pages::landing_screen.dart::LandingScreen"

class "redflag::registration_pages::landing_screen.dart::_LandingScreenState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "redflag::registration_pages::landing_screen.dart::_LandingScreenState"

class "redflag::main.dart::MyApp" {
  +State<StatefulWidget> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "redflag::main.dart::MyApp"

class "redflag::main.dart::_MyAppState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "redflag::main.dart::_MyAppState"

class "redflag::nav_pages_UI::activatePage.dart::activationPage" {
  +State<activationPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "redflag::nav_pages_UI::activatePage.dart::activationPage"

class "redflag::nav_pages_UI::activatePage.dart::_activationPageState" {
  -RingerModeStatus _soundMode
  +void initState()
  +void permissionsInit()
  -Future<void> _setSilentMode()
  +Widget build()
}

"redflag::nav_pages_UI::activatePage.dart::_activationPageState" o-- "sound_mode::utils::ringer_mode_statuses.dart::RingerModeStatus"
"flutter::src::widgets::framework.dart::State" <|-- "redflag::nav_pages_UI::activatePage.dart::_activationPageState"

class "redflag::nav_pages_UI::termination::termenationPage.dart::terminationPage" {
  +State<terminationPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "redflag::nav_pages_UI::termination::termenationPage.dart::terminationPage"

class "redflag::nav_pages_UI::termination::termenationPage.dart::_terminationPageState" {
  +void initState()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "redflag::nav_pages_UI::termination::termenationPage.dart::_terminationPageState"

class "redflag::nav_pages_UI::profilePage.dart::profilePage" {
  +State<profilePage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "redflag::nav_pages_UI::profilePage.dart::profilePage"

class "redflag::nav_pages_UI::profilePage.dart::_profilePageState" {
  +User? user
  +Users loggedInUser
  +int? ecNum
  +void initState()
  +Widget build()
  +Future<void> logout()
  +Future<void> deleteEmergencyContact()
}

"redflag::nav_pages_UI::profilePage.dart::_profilePageState" o-- "firebase_auth::firebase_auth.dart::User"
"redflag::nav_pages_UI::profilePage.dart::_profilePageState" o-- "redflag::Users.dart::Users"
"flutter::src::widgets::framework.dart::State" <|-- "redflag::nav_pages_UI::profilePage.dart::_profilePageState"

class "redflag::nav_pages_UI::reportsPage.dart::reportsPage" {
  +String caseNumb
  +State<reportsPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "redflag::nav_pages_UI::reportsPage.dart::reportsPage"

class "redflag::nav_pages_UI::reportsPage.dart::_reportsPageState" {
  +User? user
  +Users loggedInUser
  +AudioPlayer audioPlayer
  +bool isPlaying
  -String _filePath
  +String locationLink
  +void dispose()
  +void initState()
  -void _onPlayButtonPressed()
  +Widget build()
}

"redflag::nav_pages_UI::reportsPage.dart::_reportsPageState" o-- "firebase_auth::firebase_auth.dart::User"
"redflag::nav_pages_UI::reportsPage.dart::_reportsPageState" o-- "redflag::Users.dart::Users"
"redflag::nav_pages_UI::reportsPage.dart::_reportsPageState" o-- "audioplayers::src::audioplayer.dart::AudioPlayer"
"flutter::src::widgets::framework.dart::State" <|-- "redflag::nav_pages_UI::reportsPage.dart::_reportsPageState"

class "redflag::nav_pages_UI::mapPage.dart::mapPage" {
  +State<mapPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "redflag::nav_pages_UI::mapPage.dart::mapPage"

class "redflag::nav_pages_UI::mapPage.dart::_mapPageState" {
  -Completer<GoogleMapController> _controller
  +List<MarkerId> listMarkerIds
  +Map<MarkerId, Marker> markers
  +void initState()
  +Widget build()
}

"redflag::nav_pages_UI::mapPage.dart::_mapPageState" o-- "dart::async::Completer<GoogleMapController>"
"flutter::src::widgets::framework.dart::State" <|-- "redflag::nav_pages_UI::mapPage.dart::_mapPageState"

class "redflag::nav_pages_UI::nav.dart::NavScreen" {
  +State<StatefulWidget> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "redflag::nav_pages_UI::nav.dart::NavScreen"

class "redflag::nav_pages_UI::nav.dart::_NavScreenState" {
  +GeoLocatorService locationService
  +int currentIndex
  +List<dynamic> pages
  +Widget build()
}

"redflag::nav_pages_UI::nav.dart::_NavScreenState" o-- "redflag::locations::location_service.dart::GeoLocatorService"
"flutter::src::widgets::framework.dart::State" <|-- "redflag::nav_pages_UI::nav.dart::_NavScreenState"

class "redflag::nav_pages_UI::add_ec.dart::add" {
  +State<add> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "redflag::nav_pages_UI::add_ec.dart::add"

class "redflag::nav_pages_UI::add_ec.dart::_addState" {
  +TextEditingController emergencyContactNameEditingController
  +TextEditingController emergencyContactEmailEditingController
  +String? name
  +String? email
  +User? user
  +Users loggedInUser
  +void initState()
  +dynamic submitData()
  +dynamic clearData()
  +Widget build()
  +Future<void> logout()
}

"redflag::nav_pages_UI::add_ec.dart::_addState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"redflag::nav_pages_UI::add_ec.dart::_addState" o-- "firebase_auth::firebase_auth.dart::User"
"redflag::nav_pages_UI::add_ec.dart::_addState" o-- "redflag::Users.dart::Users"
"flutter::src::widgets::framework.dart::State" <|-- "redflag::nav_pages_UI::add_ec.dart::_addState"

class "redflag::nav_pages_UI::reports::emergencyCasesList.dart::cemrgencyCases" {
  +State<cemrgencyCases> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "redflag::nav_pages_UI::reports::emergencyCasesList.dart::cemrgencyCases"

class "redflag::nav_pages_UI::reports::emergencyCasesList.dart::_cemrgencyCasesState" {
  +User? user
  +Users loggedInUser
  +void initState()
  +Widget build()
}

"redflag::nav_pages_UI::reports::emergencyCasesList.dart::_cemrgencyCasesState" o-- "firebase_auth::firebase_auth.dart::User"
"redflag::nav_pages_UI::reports::emergencyCasesList.dart::_cemrgencyCasesState" o-- "redflag::Users.dart::Users"
"flutter::src::widgets::framework.dart::State" <|-- "redflag::nav_pages_UI::reports::emergencyCasesList.dart::_cemrgencyCasesState"

class "redflag::Emergency.dart::Emergency" {
  +dynamic caseNumber
  +dynamic endTime
  +dynamic userLocation
  +dynamic audioRecording
  +dynamic getCaseNumber
  +dynamic setCaseNumber
  +dynamic getEndTime
  +dynamic setEndTime
  +dynamic getUserLocation
  +dynamic setUserLocation
  +dynamic getAudioRecording
  +dynamic setAudioRecording
  +Map<String, dynamic> toMap()
  +dynamic sendMail()
}

class "redflag::EmergencyContacts.dart::EmergencyContacts" {
  +dynamic eFullName
  +dynamic ecEmail
  +String getFullName
  +String setFullName
  +dynamic getEcEmail
  +dynamic setEcEmail
  +Map<String, dynamic> toMap()
}

class "redflag::locations::location_service.dart::GeoLocatorService" {
  +Future<Position> getLocation()
}

class "redflag::locations::user_location.dart::UserLocation" {
  +dynamic getLocation()
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "redflag::locations::user_location.dart::UserLocation"

class "redflag::Users.dart::Users" {
  +dynamic userFirstName
  +dynamic userLastName
  +dynamic email
  +dynamic keyword
  +dynamic pin
  +List<EmergencyContacts> emergencyContacts
  +dynamic getUserFirstName
  +dynamic setUserFirstName
  +dynamic getUserLastName
  +dynamic setUserLastName
  +dynamic getEmail
  +dynamic setEmail
  +dynamic getKeyword
  +dynamic setKeyword
  +dynamic getPin
  +dynamic setPin
  +dynamic getEmergencyContacts
  +dynamic setEmergencyContacts
  +Map<String, dynamic> toMap()
}


@enduml